# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 308508746467.dkr.ecr.ap-south-1.amazonaws.com
        displayName: 'Login to AWS'
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-api'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/api/Dockerfile'
        tags: |
            $(tag)
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-client'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
        tags: |
            $(tag)
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-nginx'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'
        tags: |
            $(tag)
