# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: DKPool
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-api'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/api/Dockerfile'
        tags: |
            $(tag)
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-client'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
        tags: |
            $(tag)
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-nginx'
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'
        tags: |
            $(tag)
