# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/api/Dockerfile'
        tags: |
          api
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'DonateKartAWS'
        regionName: 'ap-south-1'
        imageSource: 'imagename'
        sourceImageName: 'api'
        repositoryName: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-api'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
        tags: |
          client
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'DonateKartAWS'
        regionName: 'ap-south-1'
        imageSource: 'imagename'
        sourceImageName: 'client'
        repositoryName: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-client'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'
        tags: |
          nginx
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'DonateKartAWS'
        regionName: 'ap-south-1'
        imageSource: 'imagename'
        sourceImageName: 'nginx'
        repositoryName: '308508746467.dkr.ecr.ap-south-1.amazonaws.com/test-nginx'